import type { Metadata } from "next";
import { montserrat, poppins } from "./fonts";
import "./globals.css";
import Header from "./components/header/Header";
import Footer from "./components/footer/Footer";


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${montserrat.variable} ${poppins.variable} overflow-x-hidden`}>
        <div className="">
        <Header/>
        {children}
        {/* <Footer/> */}
        </div>
        </body>
    </html>
  );
}
