import type { Metadata } from "next";
import { montserrat, poppins } from "./fonts";
import "./globals.css";



export const metadata: Metadata = {
  title: "Womb Watch",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${montserrat.variable} ${poppins.variable} transaprentscroll overflow-y-scroll overflow-x-hidden bg-white`}>
        <div className="">
        {/* <Header/> */}
        {children}
        {/* <Footer/> */}
        </div>
        </body>
    </html>
  );
}
